'use strict';

/**
 * DAY 5 — GitHub Code Search Scanner
 *
 * Uses GitHub Search API to proactively find AI-generated repos
 * that contain known secret patterns — BEFORE they show up in Events.
 *
 * Searches for:
 *  - AI tool signatures in code (cursorrules, bolt.new, etc.)
 *  - Known secret prefix patterns (sk-proj-, ghp_, AKIA, etc.)
 *  - Recent pushes with suspicious file names (.env committed, etc.)
 *
 * Rate limit: 30 req/min authenticated search API
 * We stay well within limits with built-in delays.
 */

const { getClient } = require('../utils/github-client');
const logger = require('../utils/logger');

// Search queries for AI-generated repos with potential secrets
const SEARCH_QUERIES = [
  // AI signatures + common secret file names
  'filename:.env "sk-proj-" pushed:>2024-01-01',
  'filename:.env "AKIA" pushed:>2024-01-01',
  'filename:.env "ghp_" pushed:>2024-01-01',
  '.cursorrules filename:.env',
  'CLAUDE.md filename:.env',
  '"built with bolt.new" filename:.env',
  '"generated by lovable" filename:.env',
  '"replit agent" filename:.env',
  'filename:.cursorrules filename:.env',
  // Direct secret pattern searches
  '"sk-proj-" extension:env',
  '"sk-ant-api" extension:env',
  '"AKIA" "aws_secret_access_key" extension:env',
  '"SG." extension:env sendgrid',
  '"xoxb-" extension:env',
  '"telegram" "bot_token" extension:env',
  // Config files with hardcoded secrets
  '"openai_api_key" "sk-" extension:js -test',
  '"OPENAI_API_KEY" "sk-" extension:py -test',
  '"stripe_secret" "sk_live_" extension:js',
  '"discord_token" extension:env',
  '"DATABASE_URL" "postgresql://" extension:env',
  '"mongodb+srv://" extension:env',
];

class GitHubSearchScanner {
  constructor() {
    this.client = getClient();
    this.delay = 4000; // 4s between searches (safe for 30/min limit)
  }

  /**
   * Run all search queries and return unique repo names to scan
   * @returns {Promise<string[]>} - array of "owner/repo" strings
   */
  async findTargetRepos() {
    const repos = new Set();
    logger.info(`[SearchScanner] Running ${SEARCH_QUERIES.length} GitHub Code Search queries`);

    for (const query of SEARCH_QUERIES) {
      try {
        const found = await this._searchCode(query);
        for (const r of found) repos.add(r);
        logger.debug(`[SearchScanner] Query "${query.substring(0,50)}..." → ${found.length} repos`);
        await this._sleep(this.delay);
      } catch (err) {
        logger.warn(`[SearchScanner] Query failed: ${err.message}`);
        if (err.response?.status === 403) {
          logger.warn('[SearchScanner] Rate limited — waiting 60s');
          await this._sleep(60_000);
        }
      }
    }

    logger.info(`[SearchScanner] Found ${repos.size} unique target repos`);
    return [...repos];
  }

  /**
   * Search code and return unique repo names
   */
  async _searchCode(query) {
    const repos = new Set();
    try {
      const resp = await this.client.get('/search/code', {
        params: {
          q: query,
          per_page: 30,
          sort: 'indexed',
          order: 'desc'
        }
      });

      const items = resp.data?.items || [];
      for (const item of items) {
        const repoName = item.repository?.full_name;
        if (repoName) repos.add(repoName);
      }
    } catch (err) {
      // 422 = query validation error, skip
      if (err.response?.status !== 422) throw err;
    }
    return [...repos];
  }

  /**
   * Search for recently-created AI repos specifically
   * Uses Repos search API which has different rate limits
   */
  async findRecentAIRepos() {
    const repos = [];
    const queries = [
      'topic:bolt.new pushed:>2024-06-01',
      'topic:lovable pushed:>2024-06-01',
      'topic:cursor-ai pushed:>2024-06-01',
      '"built with v0" in:readme pushed:>2024-06-01',
      '"generated by lovable" in:readme pushed:>2024-06-01',
      'filename:.cursorrules pushed:>2024-06-01',
    ];

    for (const query of queries) {
      try {
        const resp = await this.client.get('/search/repositories', {
          params: {
            q: query,
            sort: 'updated',
            order: 'desc',
            per_page: 20
          }
        });
        const items = resp.data?.items || [];
        for (const item of items) {
          repos.push({
            repoName: item.full_name,
            repoUrl: item.html_url,
            pushedAt: item.pushed_at,
            description: item.description || '',
            stars: item.stargazers_count,
            isAI: true,
            aiConfidence: 80,
            aiSignals: { searchQuery: query }
          });
        }
        await this._sleep(3000);
      } catch (err) {
        logger.debug(`[SearchScanner] Repo search error: ${err.message}`);
        await this._sleep(10_000);
      }
    }

    // Deduplicate
    const seen = new Set();
    return repos.filter(r => {
      if (seen.has(r.repoName)) return false;
      seen.add(r.repoName);
      return true;
    });
  }

  _sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

module.exports = GitHubSearchScanner;
